### PR TITLE
Clean up grammar

### PR DESCRIPTION
**Pull request by tursunova**
This PR  generates C file using Ragel State Machine Compiler version 6.10 from the grammar in https://github.com/google/emoji-segmenter/pull/7 from @behdad.

### CODE REVIEW

**Review by drott — APPROVED** [review]
LGTM

**Comment by behdad** [comment]
@tursunova Can you also please add `#include <stdbool.h>` and rebuild? The code uses `bool`, `true`, and `false`.

**Comment by behdad** [comment]
@tursunova Can you also port the `EMOJI_LINKAGE` change from my PR? Without it the compiling the `.c` file drops the `static` function from the final object.

**Comment by tursunova** [comment]
@behdad Sure, uploaded changes in https://github.com/google/emoji-segmenter/pull/10 (hope that's what you meant). Sorry, but to be honest I didn't understood why we need `EMOJI_LINKAGE` macro, don't we want `scan_emoji_presentation` to always be static?

**Comment by drott** [comment]
> Sorry, but to be honest I didn't understood why we need `EMOJI_LINKAGE` macro, don't we want `scan_emoji_presentation` to always be static?

See https://github.com/google/emoji-segmenter/pull/7/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R13 - for the local build to determin size @behdad sets EMOJI_LINKAGE to empty. If this is set to static, the compiler/linker determine that noone uses the function outside the compiled file, and it gets dropped from the `.o` file, so size cannot be measured.

**Comment by tursunova** [comment]
Ah, got it, thanks, Dominik.

**Pull request merged**
